version: '3.8'
services:
  redis:
    image: 'redislabs/redismod:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG,HSCAN
    volumes: 
      - ./redis/redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: always
  backend:
    build:
      context: .
    environment:
      - NODE_ENV=development
    volumes: 
      - ./app:/home/node/app
    ports:
      - 8081:8080
    restart: always